export const CHANGECATEGORY="CHANGECATEGORY";
export const GETCATEGORIESSUCCESS="GETCATEGORIESSUCCESS";
export const GETPRODUCTSSUCCESS="GETPRODUCTSSUCCESS";
export const ADDTOCART="ADDTOCART";
export const REMOVEFROMCART="REMOVEFROMCART";
