export const CHANGECATEGORY="CHANGECATEGORY";
export const GETCATEGORIESSUCCESS="GETCATEGORIESSUCCESS";

export const GETPRODUCTSSUCCESS="GETPRODUCTSSUCCESS";
export const CREATEPRODUCTSSUCCESS="CREATEPRODUCTSSUCCESS";
export const UPDATEPRODUCTSSUCCESS="UPDATEPRODUCTSSUCCESS";

export const ADDTOCART="ADDTOCART";
export const REMOVEFROMCART="REMOVEFROMCART";
